# Known keys
keys:
  - &admin age1uc6vmg6ruz6ky0u4s3s8d58gc3j4gramazz0k7ea9zyzxmldncfsnyv4nl
  - &larsg age1w7stgltn2stl94ap045qrzufmy9x9wuqnzrlug60v58g5j8m6c3qym8uxy

# Rules for how to encrypt files based on their path
creation_rules:
  # All files in /secrets with extension
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    # Keys that should be able to decrypt this secret
    key_groups:
      - age:
          - *admin
          - *larsg
